import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import {
  Box,
  Button,
  Container,
  Divider,
  Paper,
  TextField,
  Typography,
} from "@mui/material";
import { useState } from "react";
import axios from "axios";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  const [userPrompt, setUserPrompt] = useState("");
  const [loading, setLoading] = useState(false);
  const [response, setResponse] = useState("");

  const handleSubmit = async () => {
    setLoading(true);
    const data = {
      userPrompt,
    };
    try {
      console.log(data);
      const res = await axios.post("/api/create-site", data);
      console.log(res.data);
      router.push("/generated/index.html");
      setResponse(res.data.message);
    } catch (error) {
      console.error(error);
    }
    setLoading(false);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Container>
          <Typography variant="h1" component="h1">
            PromptSite
          </Typography>
          <Typography variant="h2" component="h2">
            A simple, free, and open-source site generator using gpt 4.
          </Typography>
          <Typography variant="h3" component="h3">
            Create a site in seconds.
          </Typography>
          <Typography variant="h4" component="h4">
            No coding required.
          </Typography>
          <Typography variant="h5" component="h5">
            No hosting required.
          </Typography>
          <Typography variant="h6" component="h6">
            No maintenance required.
          </Typography>
          <Divider
            sx={{
              margin: "1rem 0",
            }}
          />
          <Typography variant="body1" component="p">
            Enter Your Prompt Below
          </Typography>
          <Box sx={{ py: 2 }}>
            <TextField
              id="outlined-basic"
              label="Outlined"
              variant="outlined"
              multiline
              rows={8}
              fullWidth
              value={userPrompt}
              onChange={(e) => setUserPrompt(e.target.value)}
            />
            <Button
              sx={{
                mt: 1,
              }}
              variant="contained"
              onClick={handleSubmit}
            >
              Submit
            </Button>
          </Box>
          <Typography
            color="white"
            sx={{
              whiteSpace: "pre-wrap",
            }}
          >
            response:
            {response}
          </Typography>
        </Container>
      </main>
    </>
  );
}
